-- MySQL Script generated by MySQL Workbench
-- seg 24 mai 2021 17:38:30
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_salutem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_salutem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_salutem` ;
USE `db_salutem` ;

-- -----------------------------------------------------
-- Table `db_salutem`.`tb_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_salutem`.`tb_grupo` (
  `idGrupo` INT NOT NULL AUTO_INCREMENT,
  `tema` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `img_grupo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idGrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_salutem`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_salutem`.`tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `fk_grupo` INT NOT NULL,
  `crm` VARCHAR(6) NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  INDEX `fk_tb_usuario_tb_grupo1_idx` (`fk_grupo` ASC),
  UNIQUE INDEX `crm_UNIQUE` (`crm` ASC),
  CONSTRAINT `fk_tb_usuario_tb_grupo1`
    FOREIGN KEY (`fk_grupo`)
    REFERENCES `db_salutem`.`tb_grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_salutem`.`tb_postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_salutem`.`tb_postagem` (
  `id_postagem` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `url_imagem` VARCHAR(255) NULL,
  `especialidade` VARCHAR(45) NOT NULL,
  `fk_usuario_criador` INT NOT NULL,
  `fk_grupo` INT NOT NULL,
  PRIMARY KEY (`id_postagem`),
  INDEX `fk_tb_postagem_tb_usuario1_idx` (`fk_usuario_criador` ASC),
  INDEX `fk_tb_postagem_tb_grupo1_idx` (`fk_grupo` ASC),
  CONSTRAINT `fk_tb_postagem_tb_usuario1`
    FOREIGN KEY (`fk_usuario_criador`)
    REFERENCES `db_salutem`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagem_tb_grupo1`
    FOREIGN KEY (`fk_grupo`)
    REFERENCES `db_salutem`.`tb_grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
